# Site settings
title: Protviz Documentation
description: A Python package for protein annotation visualization.
baseurl: "/protviz" # The subpath of your site, e.g. /blog
url: "https://paulynamagana.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: just-the-docs # Use the just-the-docs theme (supported by github-pages gem)

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation (customize as needed)
aux_links:
  "Protviz on GitHub":
    - "//github.com/paulynamagana/protviz"

# Footer content
footer_content: "Copyright &copy; {{ site.time | date: '%Y' }} {{ site.title }}. All rights reserved."

# Plugins are typically managed by the 'github-pages' gem, so no need to list them here
# unless you have custom ones not included in github-pages.
# For just-the-docs, the necessary plugins like jekyll-feed, jekyll-seo-tag,
# and jekyll-last-modified-at are usually handled.
# If you find a specific feature missing, you might need to add a plugin here,
# but start without them for maximum compatibility.
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-last-modified-at