# Site settings
title: Protviz Documentation
description: A Python package for protein annotation visualization.
baseurl: "/protviz" # The subpath of your site, e.g. /blog
url: "https://paulynamagana.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs # Use the remote theme explicitly


defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation (customize as needed)
aux_links:
  "Protviz on GitHub":
    - "//github.com/paulynamagana/protviz"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2025 Paulyna Magaña.'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark


# Plugins required for remote themes and other features
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # This plugin is crucial for remote themes
  - jekyll-last-modified-at # Recommended for just-the-docs

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false