# Site settings
title: Protviz Documentation
description: A Python package for protein annotation visualization.
baseurl: "/protviz" # The subpath of your site, e.g. /blog
url: "https://paulynamagana.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs # Use the remote theme explicitly

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation (customize as needed)
aux_links:
  "Protviz on GitHub":
    - "//github.com/paulynamagana/protviz"

# Footer content
footer_content: "Copyright &copy; {{ site.time | date: '%Y' }} {{ site.title }}. All rights reserved."

# Plugins required for remote themes and other features
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # This plugin is crucial for remote themes
  - jekyll-last-modified-at # Recommended for just-the-docs
